### ISSUE TITLE
Support for components from code blocks

### ISSUE THREAD

**Issue by susnux** [flingyp/vitepress-demo-preview#13]
It would be nice to support previewing code blocks, e.g. generating preview for the component in following markdown file:

````markdown
# My component
some text, see example:
```vue
<template>
<!-- -->
</template>
<script>
// ...
</script>
```
````

**Comment by flingyp** [comment]
It is great idea. I can spent time to research it.

**Comment by flingyp** [comment]
The function need to move this sfc componet into default slot of component, but I don't more ideas to achieve this.
