### ISSUE TITLE
dev可以正常展示组件，build:docs报错，Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by crazyguagua** [flingyp/vitepress-demo-preview#14]
"vitepress": "^1.0.0-alpha.30"，
 "@vitepress-demo-preview/component": "^2.1.0",
    "@vitepress-demo-preview/plugin": "^1.1.6",

**Comment by flingyp** [comment]
能否给出一个Demo示例出来？

**Comment by SamWeichangyue** [comment]
@flingyp 最小复现：https://github.com/SamWeichangyue/vitePressDemo.git

**Comment by SamWeichangyue** [comment]
> @SamWeichangyue 我跑了你提供的Demo 并没有出现问题
> ![image](https://user-images.githubusercontent.com/57666140/218126413-142abeff-6cb0-4f0b-aa22-d24ad24ef1dc.png)

我猜应该是pnpm的node_modules安装策略问题，我加了shamefully-hoist=true 就没问题了
