### ISSUE TITLE
An error is reported when two files with the same name are quoted

### ISSUE THREAD

**Issue by fangzhongya** [flingyp/vitepress-demo-preview#15]
An error is reported when two files with the same name are quoted
![image](https://user-images.githubusercontent.com/41263881/220334841-64ef428d-cbba-4e88-a6c9-c326ee10280b.png)

## 组件 1

:::preview 标题说明 || 使用说明

demo-preview=../../case/components/cs-props/cs/index.vue

:::

## 组件 2

:::preview 标题说明 || 使用说明

demo-preview=../../case/components/cs-title/cs/index.vue

:::

**Comment by flingyp** [comment]
是的，应该是有这样的问题。你可以先给组件命名不同。
我有时间会立马修复的，感谢。

**Comment by flingyp** [comment]
@fangzhongya 问题已修复，你可以试试。

**Comment by fangzhongya** [comment]
已经测试没有问题了，有效率啊，
我看了下代码，我在本地包加了个时间戳的解决了
我已经创建一个分支打算提交时，看你已经改了就算了
