### ISSUE TITLE
打包报错，ERROR: Syntax error，而且不是100%报错，10次有9次报错，什么原因？

### ISSUE THREAD

**Issue by cavellpotter** [flingyp/vitepress-demo-preview#17]
![image](https://user-images.githubusercontent.com/49619105/223445849-5ae37a64-aa67-46e4-b880-3c67b11fa459.png)

**Comment by flingyp** [comment]
兄弟，这样我也很难看出来是包的问题还是其他的问题呀。
能不能提供一个最小实例Demo？

**Comment by cavellpotter** [comment]
我知道是什么问题了，config.ts里加上lastUpdated: true就会报错，去掉就好了

**Comment by cavellpotter** [comment]
加上lastUpdated: true，编译的时候好像对md失效了

**Comment by cavellpotter** [comment]
但是加上lastUpdated: true，同时在md中去掉preview组件，也可以成功，貌似preview组件和lastUpdated: true这个参数冲突一样

**Comment by flingyp** [comment]
这样昂，抽时间看下。谢谢啦

**Comment by flingyp** [comment]
兄弟能提供一个仓库吗？我想复现下你提的这个问题

**Comment by cavellpotter** [comment]
https://github.com/cavellpotter/vitepress-demo-preview-test.git
![image](https://user-images.githubusercontent.com/49619105/223706388-30a26dbd-7294-4318-94ac-7f4e094ece63.png)

**Comment by zy823957866** [comment]
终于解决了，另外2.2.0版本有个css报错。
``` css
 justify-content: end
```

**Comment by supbose** [comment]
> 终于解决了，另外2.2.0版本有个css报错。
> 
> ```css
>  justify-content: end
> ```

兄弟怎么解决的呢?

**Comment by flingyp** [comment]
> 终于解决了，另外2.2.0版本有个css报错。
> 
> ```css
>  justify-content: end
> ```

额，我没有发现关于CSS上的报错。
既然知道哪里有报错了，有没有兴趣来提个PR呢。

**Comment by supbose** [comment]
我也没发现css报错!!😊

**Comment by supbose** [comment]
> https://github.com/cavellpotter/vitepress-demo-preview-test.git

看看这个和更新时间冲突打包报错的问题呢?亲!!

**Comment by flingyp** [comment]
> > https://github.com/cavellpotter/vitepress-demo-preview-test.git
> 
> 看看这个和更新时间冲突打包报错的问题呢?亲!!

这个问题我测试过了，我在仓库的example项目上没有出现过一次这种问题。但是用上面这个兄弟仓库的也试过确实出现打错错误的情况，但是也有打包成功过。

这种情况我真不知道从哪里下手，哭死。

**Comment by supbose** [comment]
> > > https://github.com/cavellpotter/vitepress-demo-preview-test.git
> > 
> > 
> > 看看这个和更新时间冲突打包报错的问题呢?亲!!
> 
> 这个问题我测试过了，我在仓库的example项目上没有出现过一次这种问题。但是用上面这个兄弟仓库的也试过确实出现打错错误的情况，但是也有打包成功过。
> 
> 这种情况我真不知道从哪里下手，哭死。

还有一个情况我测试过,如果`docs:build": "vitepress build"`打包就不会出错.`docs:build": "vitepress build docs"`这样就出错.总的来说.关闭更新时间就OK的.😊😊😊😊😊

**Comment by flingyp** [comment]
@supbose @zy823957866 @cavellpotter Hello，有空帮忙测试下，@vitepress-demo-preview/plugin 安装到 v1.1.9 然后再试试打包看看会不会出现这种问题。感谢啦！
