### ISSUE TITLE
解析报错，componentName为空

### ISSUE THREAD

**Issue by lihuabest** [flingyp/vitepress-demo-preview#18]
按照文档配置报错，组件名称为空导致解析失败。

![微信截图_20230410174833](https://user-images.githubusercontent.com/1559817/230878355-11db9708-eddb-40dc-b408-d1263e320c55.png)
![微信图片_20230410174906](https://user-images.githubusercontent.com/1559817/230878363-2e7b8467-2c5f-43f1-a0e3-c18657ee2af6.png)

**Comment by flingyp** [comment]
组件名为空？我能看看你是怎么使用的吗？

**Comment by lihuabest** [comment]
测试发现需要升级node版本，原来版本是14.18.2，升级到16.14.0就好了，node的版本要求其实可以多测试一下。

新的问题，组件显示为空白，其中vitepress@1.0.0-alpha.65
![微信截图_20230411113206](https://user-images.githubusercontent.com/1559817/231049283-35bf5cc0-0013-4c47-a46f-393349f43c7d.png)

**Comment by flingyp** [comment]
@lihuabest  Hello，我可以了解下你出现这种问题的示例代码吗？

**Comment by heshan0927** [comment]
> 测试发现需要升级node版本，原来版本是14.18.2，升级到16.14.0就好了，node的版本要求其实可以多测试一下。
> 
> 新的问题，组件显示为空白，其中vitepress@1.0.0-alpha.65 ![微信截图_20230411113206](https://user-images.githubusercontent.com/1559817/231049283-35bf5cc0-0013-4c47-a46f-393349f43c7d.png)
碰到了同样的问题，应该是组件的文件名和 component name 不一致导致的。参考源码中的composeComponentName方法，是根据path来组合组件名的。看截图的例子，是把组件处理成了<table>导致无法渲染。

建议可以支持传入自定义组件名称：）
