### ISSUE TITLE
报错路径必须接受string

### ISSUE THREAD

**Issue by Richard-Zhang1019** [flingyp/vitepress-demo-preview#19]
使用的时候传的都是字符串 
可能是版本问题 之前使用的是1.0.0-alpha.69是没有问题的 升级到1.0.0-alpha.75之后就会启动时报这个错
<img width="509" alt="image" src="https://user-images.githubusercontent.com/76982270/235835763-8d4edab1-7474-46e6-859f-20980d5e82a6.png">
<img width="936" alt="image" src="https://user-images.githubusercontent.com/76982270/235835876-78f810f8-d789-4c02-babd-ae48ba82dbd2.png">

**Comment by flingyp** [comment]
感谢反馈，有空会处理。谢谢

**Comment by flingyp** [comment]
@Richard-Zhang1019  可否可以提供一个最小复现的代码仓库？

我将项目中example的vitepress升级到最新版本后并没有发现问题。

**Comment by Richard-Zhang1019** [comment]
> @Richard-Zhang1019 可否可以提供一个最小复现的代码仓库？
> 
> 我将项目中example的vitepress升级到最新版本后并没有发现问题。

那可能是我自己这里的问题
https://github.com/lucky-design-org/lucky-design/tree/fix
我在fix分支的改动 使用最新版本的vitepress时 pnpm run dev 会报错提示
<img width="506" alt="image" src="https://user-images.githubusercontent.com/76982270/235939807-409d3db0-1ddd-406a-a89b-56d32f1cb0e2.png">

**Comment by flingyp** [comment]
@Richard-Zhang1019  这和Vitepress版本无关，或许是Vitepress的Bug

我在调试的时候发现如下问题

在`@vitepress-demo-preview/plugin` 需要使用到Vitepress提供的env.path变量，但是我在调试的时候发现如果文档中配置了[Local Search](https://vitepress.dev/reference/default-theme-search#local-search)时，env 中会丢失第一张截图的三个变量。

![image](https://user-images.githubusercontent.com/57666140/236105996-cd99aaf3-c1a2-4f23-a28c-261c26ece6ae.png)

![image](https://user-images.githubusercontent.com/57666140/236106117-ff635575-3de4-403f-9b99-ef3907c6ba3d.png)

**Comment by Richard-Zhang1019** [comment]
> @Richard-Zhang1019 这和Vitepress版本无关，或许是Vitepress的Bug
> 
> 我在调试的时候发现如下问题
> 
> 在`@vitepress-demo-preview/plugin` 需要使用到Vitepress提供的env.path变量，但是我在调试的时候发现如果文档中配置了[Local Search](https://vitepress.dev/reference/default-theme-search#local-search)时，env 中会丢失第一张截图的三个变量。
> 
> ![image](https://user-images.githubusercontent.com/57666140/236105996-cd99aaf3-c1a2-4f23-a28c-261c26ece6ae.png)
> 
> ![image](https://user-images.githubusercontent.com/57666140/236106117-ff635575-3de4-403f-9b99-ef3907c6ba3d.png)

感谢您的回复

**Comment by flingyp** [comment]
The question was built at vitepress and you can found it at  [#2313](https://github.com/vuejs/vitepress/issues/2313)
