### ISSUE TITLE
when use local search will lead to program breakdown

### ISSUE THREAD

**Issue by Richard-Zhang1019** [flingyp/vitepress-demo-preview#26]
Only when I use local search will the program breakdown. After closing the local search, the program will not breakdown

version here:
<img width="587" alt="image" src="https://github.com/flingyp/vitepress-demo-preview/assets/76982270/ea336d1b-7b6e-4d1d-a0b6-401a4bd5a6c9">
<img width="562" alt="image" src="https://github.com/flingyp/vitepress-demo-preview/assets/76982270/7fb7a247-0a12-4799-9f1b-ad755cf3985a">

<img width="707" alt="image" src="https://github.com/flingyp/vitepress-demo-preview/assets/76982270/5e4a0907-4dad-4026-9cce-c157cdaf9fb9">

**Comment by flingyp** [comment]
I just try once, I feel that's vitepress's problem.

**Comment by flingyp** [comment]
After trying out the example of the project, I did not find the problem with your screenshot.

**Comment by Richard-Zhang1019** [comment]
> After trying out the example of the project, I did not find the problem with your screenshot.

哥们你没遇到我这个问题吗 使用这个包后开启本地搜索的时候就会这样报错

**Comment by flingyp** [comment]
对呀，你是添加了markdown-it-task-lists这个插件，然后开启本地搜索才报错的吗？还是只是开启本地搜索报错？

**Comment by Richard-Zhang1019** [comment]
> 

是的 只是开启本地搜索的时候会报错 把markdown-it-task-lists去掉了本地跑的时候是没有问题的 已经通过控制变量方法排除了 只有引入demo插件和本地搜索同时开启时会程序崩掉

**Comment by flingyp** [comment]
对呀，我把vitepress升级最新版本然后开启本地搜索本地运行没问题呀，打包也没问题。😂
![image](https://github.com/flingyp/vitepress-demo-preview/assets/57666140/55c705be-e054-4407-aa4f-b2f935b4b4ad)

**Comment by Richard-Zhang1019** [comment]
> 对呀，我把vitepress升级最新版本然后开启本地搜索本地运行没问题呀，打包也没问题。😂 ![image](https://user-images.githubusercontent.com/57666140/246653853-55c705be-e054-4407-aa4f-b2f935b4b4ad.png)

woc 稍等下我再去试试

**Comment by Richard-Zhang1019** [comment]
> 对呀，我把vitepress升级最新版本然后开启本地搜索本地运行没问题呀，打包也没问题。😂 ![image](https://user-images.githubusercontent.com/57666140/246653853-55c705be-e054-4407-aa4f-b2f935b4b4ad.png)

That's amazing 我新开了repo去试了下发现是没有问题的 我自己的项目升级的时候不知道哪里配置出问题了一直报错😭
