### ISSUE TITLE
[Feature Request]: title和description非必填

### ISSUE THREAD

**Issue by StreakingMan** [flingyp/vitepress-demo-preview#29]
根据源码中的正则，不把 path title description 三个属性都填上，会导致path解析失败

```ts
// componentPreview.ts 
// line 13~17
const getPropsReg1 =
  /^<preview (path|title|description)=(.*) (path|title|description)=(.*) (path|title|description)=(.*)><\/preview>$/

const getPropsReg2 =
  /^<preview (path|title|description)=(.*) (path|title|description)=(.*) (path|title|description)=(.*) \/>$/

// line 39
  const tokenContentArr = token.content.match(getPropsReg1) || token.content.match(getPropsReg2) || []
```

只有path的时候，正则匹配为空，无法加载
![image](https://github.com/flingyp/vitepress-demo-preview/assets/30397306/080bd471-75d4-461f-929c-e439ea93c825)

期望：title和description改为可选，同时UI做相对应调整🤔️

**Comment by flingyp** [comment]
`@vitepress-demo-preview/plugin@1.2.1`  已支持title和description可选
`@vitepress-demo-preview/component@2.3.2`  组件样式做了调整

具体使用参考README.md
![image](https://github.com/flingyp/vitepress-demo-preview/assets/57666140/a8b1755c-c9f6-4e56-969a-ef285743f6f2)
