### ISSUE TITLE
引入层级为二层时会报错 一层时正常使用

### ISSUE THREAD

**Issue by Richard-Zhang1019** [flingyp/vitepress-demo-preview#33]
<img width="262" alt="image" src="https://github.com/flingyp/vitepress-demo-preview/assets/76982270/cb23a90e-dcd1-4f09-a793-8ca6a5f561f2">

我这里在目录 /notes/vue/n-003.md中引用 /examples/e-007.vue时 

```
<preview path="../../examples/e-008.vue" title="" description="" />
```

此时会报错 如果在上一层引入时就不会报错

```
<preview path="../examples/e-008.vue" title="" description="" />
```

**Comment by flingyp** [comment]
报错信息有吗，有截图吗？

**Comment by flingyp** [comment]
已经定位问题了，我会修复它。

**Comment by Richard-Zhang1019** [comment]
> @Richard-Zhang1019 升级 @vitepress-demo-preview/plugin 版本到 v1.2.2 再试试

感谢修复 这个插件为我提供了很大的帮助
