### ISSUE TITLE
vitepress@1.0.0-rc.45 版本path传入文件代码不显示

### ISSUE THREAD

**Issue by strawberryPig** [flingyp/vitepress-demo-preview#34]
- button.md
```md
<ClientOnly>
<demo path='../demos/button-demo-1.vue' title="测试" description='哈哈哈'/>
</ClientOnly>
```

- demos/button-demo-1.vue
```vue
<tempalte>
  <div>aaa</div>
</tempalte>

```

[
<img width="833" alt="企业微信20240308-172339@2x" src="https://github.com/flingyp/vitepress-demo-preview/assets/140479054/782a27db-9326-475c-b091-94a84a48e9a8">
](url)

**Comment by flingyp** [comment]
你应该是写错了 `<demo path='../demos/button-demo-1.vue' title="测试" description='哈哈哈'/>` 改成了 `<preview path='../demos/button-demo-1.vue' title="测试" description='哈哈哈'/>` 再试试

**Comment by frontHu** [comment]
@flingyp 遇见同样的问题
```
// theme/index.ts
import { AntDesignContainer, ElementPlusContainer, NaiveUIContainer } from '@vitepress-demo-preview/component'
export default {
  extends: DefaultTheme,
  enhanceApp({ app }) {
    app.use(createI18n({ locale: 'en-US', legacy: false }))
    app.component('demo-preview', NaiveUIContainer)
    // ....
  }
}

```
// basic.md
<demo-preview path="../components/BasicTable/basic.vue" title="222" description='ddd'></demo-preview> 

````

```

**Comment by flingyp** [comment]
@frontHu  bro，仔细看下README的示例，不是 `<demo-preview>`

**Comment by strawberryPig** [comment]
@flingyp 你的这个回答有点过于应付，正常没人会犯这种基础的把名字写错的问题，而且如果写错了就什么都不会展示，现在是组件能加载出来只有折叠展开里的源码不展示，很明显是 vitepress-demo-preview 的问题，希望能自己下个新版的vitepress 排查一下

**Comment by flingyp** [comment]
@strawberryPig  那么请你看清楚你所提供的代码块和README里写的使用方式是否一致呢？还有我并没有义务和花时间去处理你所提出的问题，所以我也不觉得我的回复过于应付。如果你觉得这个项目有什么BUG或不足的地方，你也可以尝试修复它，因为我也不能保证它让每个使用者满意。
![image](https://github.com/flingyp/vitepress-demo-preview/assets/57666140/e37d2c0e-e726-4d52-acfc-35b3dcd27766)

**Comment by frontHu** [comment]
@flingyp 可以了，感谢，我以为是按照通过app.component('demo-preview', NaiveUIContainer),这里注册的name去使用组件
