### ISSUE TITLE
vitepress build docs 之后服务好像没有停止掉

### ISSUE THREAD

**Issue by wangxiaoze-view** [flingyp/vitepress-demo-preview#39]
``` json
// 使用的版本
{
 "@vitepress-demo-preview/component": "^2.3.2",
    "@vitepress-demo-preview/plugin": "^1.2.3"
    }
```

我使用 的是最新的版本, 但是在执行build命令会发现：
![image](https://github.com/user-attachments/assets/e9a1b062-c78d-4cd2-99e9-38d8fc4bce88)

**build complete in 4.71s.** 提示打包完成了，但是服务还在，没有停止掉；

但是我把这俩个插件删掉之后，再次build 服务就停止了；

我不确定的是什么原因导致的?

**Comment by flingyp** [comment]
![image](https://github.com/user-attachments/assets/de69a33d-8fc8-4b1f-b1f6-57c435eb52fe)

我这边升级了下 example 下的 vitepress 版本后，打包了一下没出现你这个问题

**Comment by wangxiaoze-view** [comment]
> ![image](https://private-user-images.githubusercontent.com/57666140/358173756-de69a33d-8fc8-4b1f-b1f6-57c435eb52fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTI2NjIsIm5iZiI6MTcyMzcxMjM2MiwicGF0aCI6Ii81NzY2NjE0MC8zNTgxNzM3NTYtZGU2OWEzM2QtOGZjOC00YjFmLWIxZjYtNTdjNDM1ZWI1MmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4NTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhM2E4YTg4ZmY5NzZmNDliMWZiZDljMmJlN2MwYWE0M2FkNzU0ZWJiMmQ2OWNhMGFmZjA2Zjk5NjYxMjM4NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h1enzg6RYgq2Zp-l82WDu626tezXfA0VNeony6R32BI)
> 
> 我这边升级了下 example 下的 vitepress 版本后，打包了一下没出现你这个问题

好奇怪，我用vercel 部署的时候也没有停止最终的服务（晚点时候我在重新试一下），于是我临时加了一个终止的代码：

``` ts
export default defineConfig({
buildEnd() {
exit();
},
})
```
但是我不确定会不会有什么太大影响；
