### ISSUE TITLE
demo组件和自定义的组件样式冲突

### ISSUE THREAD

**Issue by xiaoxustudio** [flingyp/vitepress-demo-preview#42]
我发现在生产环境下，我自定义的组件和在 文档模式下使用demo组件预览出来的效果有差异

在排查后发现，一些css属性会和我的自定义组件有冲突：

如demo组件的样式会有 ul 、li等标签的样式，我组件内用了这些dom后，也会被影响，就造成了超出预期的效果。

**Comment by flingyp** [comment]
所以哪里的样式有冲突呢？

**Comment by xiaoxustudio** [comment]
on! 我的问题，好像是 vitepress 导致的冲突，并不是本组件的冲突
